---
# tasks file for xcp-ng_guest-utilities
- block:
  - name: Download guest-utilities tar archive
    get_url:
      url: http://{{ guest_utilities_download_path }}/xe-guest-utilities_{{ guest_utilities_version }}.tgz
      dest: /tmp/
      mode: 0440
    environment:
      http_proxy: '{{ http_proxy|default("") }}'

  - name: extract guest-utilities tgz archive
    unarchive:
      src: /tmp/xe-guest-utilities_{{ guest_utilities_version }}.tgz
      dest: /tmp/
      remote_src: true

  - name: install guest-utilities via script
    shell: /tmp/Linux/install.sh -n
    become: true

  - name: clean after installation
    file:
      state: absent
      path: '{{ item.path }}'
    with_items:
      - path: '/tmp/Linux/'
      - path: '/tmp/xe-guest-utilities_{{ guest_utilities_version }}.tgz'
    become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- block:
    - name: make sure old version of xe-guest_utilities are not installed
      yum:
        name:
          - xe-guest-utilities.x86_64
          - xe-guest-utilities-xenstore.x86_64
        state: absent

    - name: make sure xe-guest-utilities-latest from epel are installed
      yum:
        name: xe-guest-utilities-latest.x86_64
        state: installed
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: start and enable xen utilities
  systemd:
    name: xe-linux-distribution
    state: started
    enabled: true

- name: reboot server if defined
  reboot:
  become: true
  when: guest_utilities_reboot_after_installation
