---
# tasks file for xcp-ng_guest-utilities

- name: Download guest-utilities tar archive
  get_url:
    url: http://{{ guest_utilities_download_path }}/xe-guest-utilities_{{ guest_utilities_version }}.tgz
    dest: /tmp/
    mode: 0440
  environment:
    http_proxy: '{{ http_proxy|default("") }}'

- name: install tar if not present (centos6 doesn't come with tar preinstalled)
  package:
    name: tar
    state: present

- name: extract guest-utilities tgz archive
  unarchive:
    src: /tmp/xe-guest-utilities_{{ guest_utilities_version }}.tgz
    dest: /tmp/
    remote_src: true

- name: install guest-utilities via script
  shell: /tmp/Linux/install.sh -n
  become: true

- name: clean after installation
  file:
    state: absent
    path: '{{ item.path }}'
  with_items:
    - path: '/tmp/Linux/'
    - path: '/tmp/xe-guest-utilities_{{ guest_utilities_version }}.tgz'
  become: true

- name: reboot server if defined
  reboot:
  become: true
  when: guest_utilities_reboot_after_installation
