---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    # dependency: If this role required other roles, we could add a requirements.yml file in the default scenario directory, and Molecule would install them in this step.
    # - dependency
    - syntax
    - create
    # prepare: You can create a prepare.yml playbook in the default scenario directory and have Molecule run it during the prepare step
    # - prepare
    - converge
    - idempotence
    # side_effect: You can create a side_effect.yml playbook in the default scenario directory and have Molecule run it during the prepare step
    # - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
